version: '3.7'

networks:
  wordpress-network:

services:
  db:
    container_name: wordpress_db
    image: pavelmalachovski/mysql_ypip:latest
    environment:
       MYSQL_ROOT_PASSWORD: rootPassword
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wp-user
       MYSQL_PASSWORD: wp-pass
    ports:
      - 8889:3306
    networks:
      - wordpress-network

  phpmyadmin:
    container_name: wordpress-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USER: wp-user
      MYSQL_PASSWORD: wp-pass
      MYSQL_ROOT_PASSWORD: rootPassword
    ports:
      - 3001:80
    networks:
      - wordpress-network

  wordpress:
    container_name: wordpress-site
    depends_on:
      - db
    image: pavelmalachovski/yourphotographerinprague:latest
    ports:
      - 8888:80
      - 443:443
    environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: wp-user
       WORDPRESS_DB_PASSWORD: wp-pass
    networks:
      - wordpress-network