---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Feature-YourPhotographerInPrague-to-AWS-ElasticBeanStalk

###############################
#    Environment Parameters   #
###############################
env:
  EB_PACKAGE_S3_BUCKET_NAME: "yourphotographerinprague"
  EB_APPLICATION_NAME: "YourPhotographerInPrague"
  EB_ENVIRONMENT_NAME: "Yourphotographerinprague-env"
  DEPLOY_PACKAGE_NAME: "ypip_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central-1"

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

###############
# Set the Job #
###############
jobs:
  my_linter:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}